# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w9ESORBmSIXH85VxxC99Be5epnXWjPlj
"""

import requests
from bs4 import BeautifulSoup

pagina = requests.get('https://www.samsung.com/br/smartphones/galaxy-a/galaxy-a04e-black-64gb-sm-a042mzkhzto')
#variavel com usabilidade da biblioteca e a ferramenta de análise
site = BeautifulSoup(pagina.content, 'html.parser')

#método 1 pra armazenar um dado (no caso o nome do celular)
produtos = site.find_all('div', attrs={'class': 'pd-info'})
nome_cel = [i.find('h2').text for i in produtos]

print(nome_cel)
#daqui pra baixo ainda falta resolver o "{{price.priceWrapper.info.totalPrice}}, onde, deveria aparecer o preço"
preco = site.find('strong', class_='cost-box__price-now').get_text()
print(preco)
#segundo método para extrair dados
preco = site.find('h2', class_='pd-info__title').get_text()
print(preco)